### ISSUE TITLE
After the first download, execute the `pnpm build` command, prompt for build failure

### ISSUE THREAD

**Issue by jietester** [valaxyjs/valaxy-theme-starter#5]
Operating Steps:
0. Create a new repository from valaxy-theme-starter  (use the temeplate)
1. `git clone git@github.com:zmxlt/valaxy-theme-aurora.git`
2. `cd valaxy-theme-aurora`
3. `pnpm i` success
4. `pnpm dev` success
5. `pnpm demo` success
6. `pnpm build`  report errors

```
D:\blog\valaxy-theme-aurora\node_modules\.pnpm\vite-ssg@0.22.1_@vueuse+head@1.0.26_critters@0.0.16_vite@4.1.2_vue-router@4.1.6_vue@3.2.47\node_modules\vite-ssg\dist\shared\vite-ssg.45ed6849.cjs:1048
        throw new Error(`${kolorist.gray("[vite-ssg]")} ${kolorist.red(`Error on page: ${kolorist.cyan(route)}`)}
              ^

Error: [vite-ssg] Error on page: /:all(.*)*
Error: ENOENT: no such file or directory, open 'D:\blog\valaxy-theme-aurora\demo\dist\:all(.*)*.html'
    at D:\blog\valaxy-theme-aurora\node_modules\.pnpm\vite-ssg@0.22.1_@vueuse+head@1.0.26_critters@0.0.16_vite@4.1.2_vue-router@4.1.6_vue@3.2.47\node_modules\vite-ssg\dist\shared\vite-ssg.45ed6849.cjs:1048:15
    at async run (D:\blog\valaxy-theme-aurora\node_modules\.pnpm\vite-ssg@0.22.1_@vueuse+head@1.0.26_critters@0.0.16_vite@4.1.2_vue-router@4.1.6_vue@3.2.47\node_modules\vite-ssg\dist\shared\vite-ssg.45ed6849.cjs:629:36)

```
![image](https://user-images.githubusercontent.com/25658690/229669768-4482adde-48e6-4bcc-b522-e11027e8c5fb.png)

**Comment by YunYouJun** [comment]
Just upgrade deps, and then it works well.

I update this template.
